"""
Run the project's SQL questions against the processed dataset.

Loads data/processed/indicators.csv and data/reference/presidencies.csv into
an in-memory SQLite database, runs every file in sql/ in order, prints the
results, and writes them to output/query-results.md.

Nothing is stored on disk as a database, so there is no binary artifact to
keep in step with the CSV. The answers are rebuilt from the pipeline output
every run.

Run: python scripts/query.py   (after scripts/transform.py)
"""

import sqlite3
import sys
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
CSV_FILE = ROOT / "data" / "processed" / "indicators.csv"
PRESIDENCIES_FILE = ROOT / "data" / "reference" / "presidencies.csv"
SQL_DIR = ROOT / "sql"
RESULTS_FILE = ROOT / "output" / "query-results.md"


def build_database():
    """One in-memory database holding the processed table plus its lookup."""
    for path in (CSV_FILE, PRESIDENCIES_FILE):
        if not path.exists():
            raise SystemExit(f"{path} not found. Run scripts/transform.py first.")

    connection = sqlite3.connect(":memory:")
    pd.read_csv(CSV_FILE).to_sql("indicators", connection, index=False)
    pd.read_csv(PRESIDENCIES_FILE).to_sql("presidencies", connection, index=False)
    return connection


def read_question(sql_text):
    """The leading comment block is the business question. Show it with the result."""
    lines = []
    for line in sql_text.splitlines():
        if not line.startswith("--"):
            break
        lines.append(line.lstrip("-").strip())
    return "\n".join(lines).strip()


def to_markdown(frame):
    """Small hand-rolled renderer so the output needs no extra dependency."""
    if frame.empty:
        return "_no rows_"

    header = [str(column) for column in frame.columns]
    rows = [
        ["" if pd.isna(value) else f"{value:g}" if isinstance(value, float) else str(value)
         for value in record]
        for record in frame.itertuples(index=False)
    ]

    widths = [
        max(len(header[i]), *(len(row[i]) for row in rows))
        for i in range(len(header))
    ]
    divider = "|" + "|".join("-" * (width + 2) for width in widths) + "|"
    lines = ["| " + " | ".join(h.ljust(w) for h, w in zip(header, widths)) + " |", divider]
    lines += [
        "| " + " | ".join(cell.ljust(w) for cell, w in zip(row, widths)) + " |"
        for row in rows
    ]
    return "\n".join(lines)


def run():
    sql_files = sorted(SQL_DIR.glob("*.sql"))
    if not sql_files:
        raise SystemExit(f"no .sql files in {SQL_DIR}")

    connection = build_database()
    sections = [
        "# SQL Query Results",
        "",
        "Generated by `python scripts/query.py`. Do not edit by hand.",
        "",
        f"Source: `data/processed/indicators.csv` and `data/reference/presidencies.csv`.",
        "",
    ]

    for path in sql_files:
        sql_text = path.read_text(encoding="utf-8")
        frame = pd.read_sql_query(sql_text, connection)
        table = to_markdown(frame)

        print(f"\n=== {path.name} ===")
        print(table)

        sections += [
            f"## {path.name}",
            "",
            "```",
            read_question(sql_text),
            "```",
            "",
            table,
            "",
        ]

    connection.close()

    RESULTS_FILE.parent.mkdir(parents=True, exist_ok=True)
    RESULTS_FILE.write_text("\n".join(sections) + "\n", encoding="utf-8")
    print(f"\n{len(sql_files)} queries -> {RESULTS_FILE}")
    return 0


if __name__ == "__main__":
    sys.exit(run())
